name: movie_app
description: A new Flutter project.


publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio:
  url_launcher: ^6.1.5
  lottie: ^1.4.2
  shared_preferences:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie.json


